source ; https://www.justintodata.com/python-numpy-tutorial-basics-for-data-science/

In [2]:
import numpy as np

In [3]:
x = np.array(range(100))

In [4]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

    
    - ndim ; the number of axes (dimensions).
    
    - shape ; the dimensions of the array as a tuple. For a matrix with n rows and m columns, the shape will be (n,m).
    
    - size ; the total number of elements of the array, which eqauls to the product of the elements of shape.
    
    - dtype ; the data type of the elements in the array. More on this the Data Types sections.
    
    - itemsize ; the size in byes of each element of the array. For example, int32 has itemsize 4 (=32/4)

In [10]:
x.ndim

x.shape

x.size

x.dtype

x.itemsize

4

In [23]:
y = np.array([[1.0,2,3], [4,5,6], [7,8,9]])

y

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [26]:
y.ndim

y.shape

y.size

y.dtype

y.itemsize

8

## Sepcial Arrays(zeros, ones, full, eye)

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.full((5,5),30)

array([[30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30]])

In [36]:
x = np.array([[1,2,3],[4,5,6]])

np.full(x.shape,53)

array([[53, 53, 53],
       [53, 53, 53]])

### eye

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Data Types

In [39]:
x = np.array(range(100))

y = np.array(range(100), dtype=np.int8)

In [47]:
x

x.itemsize

4

In [48]:
y

y.itemsize

1

int8 numbers cannot have values outsize the range -128 to 127. But with int32, the range can be much large (~ to ~)

When we only need a smaller range of numeric values, setting a smaller sized data type helps save memory

## Array Manipulation

### Reshape

In [50]:
x = np.array(range(90))
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [51]:
x = x.reshape((10,9))
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [56]:
x = x.reshape((3,3,10))
x


array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]]])

Besides specifiying, one of the shape dimensions can be -1. In this case, the value is infereed from the length of the array and the remaining dimensions. Since the new shape needs to be compatible with the original one.

In [57]:
x. reshape((3,-1,10))

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]]])

## Ravel

In [59]:
x = np.array(range(90)).reshape(10,3,3) ##
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]],

       [[54, 55, 56],
        [57, 58, 59],
        [60, 61, 62]],

       [[63, 64, 65],
        [66, 67, 68],
        [69, 70, 71]],

       [[72, 73, 74],
        [75, 76, 77],
        [78, 79, 80]],

       [[81, 82, 83],
        [84, 85, 86],
        [87, 88, 89]]])

In [62]:
x.ravel() # flatten method

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

### Transpose

In [65]:
x = np.array(range(90)).reshape(10,3,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]],

       [[54, 55, 56],
        [57, 58, 59],
        [60, 61, 62]],

       [[63, 64, 65],
        [66, 67, 68],
        [69, 70, 71]],

       [[72, 73, 74],
        [75, 76, 77],
        [78, 79, 80]],

       [[81, 82, 83],
        [84, 85, 86],
        [87, 88, 89]]])

In [66]:
x.T

array([[[ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81],
        [ 3, 12, 21, 30, 39, 48, 57, 66, 75, 84],
        [ 6, 15, 24, 33, 42, 51, 60, 69, 78, 87]],

       [[ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82],
        [ 4, 13, 22, 31, 40, 49, 58, 67, 76, 85],
        [ 7, 16, 25, 34, 43, 52, 61, 70, 79, 88]],

       [[ 2, 11, 20, 29, 38, 47, 56, 65, 74, 83],
        [ 5, 14, 23, 32, 41, 50, 59, 68, 77, 86],
        [ 8, 17, 26, 35, 44, 53, 62, 71, 80, 89]]])

## Single Array Math Operations

In [67]:
x = np.array(range(1, 101))
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [73]:
x.sum()

x.min()

x.max()

x.mean()

x.std()

28.86607004772212

In [75]:
np.median(x)

np.sqrt(x)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766,
        3.31662479,  3.46410162,  3.60555128,  3.74165739,  3.87298335,
        4.        ,  4.12310563,  4.24264069,  4.35889894,  4.47213595,
        4.58257569,  4.69041576,  4.79583152,  4.89897949,  5.        ,
        5.09901951,  5.19615242,  5.29150262,  5.38516481,  5.47722558,
        5.56776436,  5.65685425,  5.74456265,  5.83095189,  5.91607978,
        6.        ,  6.08276253,  6.164414  ,  6.244998  ,  6.32455532,
        6.40312424,  6.4807407 ,  6.55743852,  6.63324958,  6.70820393,
        6.78232998,  6.8556546 ,  6.92820323,  7.        ,  7.07106781,
        7.14142843,  7.21110255,  7.28010989,  7.34846923,  7.41619849,
        7.48331477,  7.54983444,  7.61577311,  7.68114575,  7.74596669,
        7.81024968,  7.87400787,  7.93725393,  8.        ,  8.06225775,
        8.1240384 ,  8.18535277,  8.24621125,  8.30662386,  8.36

## Array Indexing and Slicing

In [77]:
x = np.array(range(100)).reshape((10,10))
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Element Selection

The most basic selection is one element; we can call the elements within the array by its corresponding index positins. Recall that the index positions start from 0. 

For example, x[0,1] is calling for the element on the first row (index position 0) and the second column(index position 1).

In [79]:
x[0, 1]

x[2, 9]

29

### Subarray Selection

This concept is most natrual to learn with a 2D array with columns and rows.

For example, to select the second row(index position 1)

In [80]:
x[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [83]:
# To select the thrid column (index position 2)

x[:, 2] ## !

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [84]:
x[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [85]:
x[:, 1:3]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])

In [86]:
x[1:3, 1:3]

array([[11, 12],
       [21, 22]])

#### advanced indexing to get particular rows. # good!

In [87]:
x[[0,3,9]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [88]:
x[[0,3,9], 2]

array([ 2, 32, 92])

## Boolean Indexing

Besides the above, we can also use boolean (T/F) indexing on NumPy arrays. It's handy for selecting the elements of an array that satisfy some condition.

In [90]:
bool_index = (x > 50)
bool_index

x[bool_index]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## Value Changes

NumPy arrays are mutable. With indexing and slicing , we can also resassign the elements within an array.

In [ ]:
x = np.array

In [110]:
#x = np.array(range(27)).reshape((3,-1,3))
x = np.array(range(1,28)).reshape((3,-1,3))

In [111]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [102]:
x[0, 0, 0] = 100
x

array([[[100,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8]],

       [[  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17]],

       [[ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26]]])

In [103]:
x[:, 1, 1] = 99 
x

array([[[100,   1,   2],
        [  3,  99,   5],
        [  6,   7,   8]],

       [[  9,  10,  11],
        [ 12,  99,  14],
        [ 15,  16,  17]],

       [[ 18,  19,  20],
        [ 21,  99,  23],
        [ 24,  25,  26]]])

In [105]:
x[:, 1, 2] = 2
x

array([[[100,   1,   2],
        [  3,  99,   2],
        [  6,   7,   8]],

       [[  9,  10,  11],
        [ 12,  99,   2],
        [ 15,  16,  17]],

       [[ 18,  19,  20],
        [ 21,  99,   2],
        [ 24,  25,  26]]])

In [106]:
x[0, :, :] = -888
x

array([[[-888, -888, -888],
        [-888, -888, -888],
        [-888, -888, -888]],

       [[   9,   10,   11],
        [  12,   99,    2],
        [  15,   16,   17]],

       [[  18,   19,   20],
        [  21,   99,    2],
        [  24,   25,   26]]])

## Multiple Arrays : Stack / Concatenation

In [108]:
x = np.array(range(10)).reshape((5,2))
x

y = np.array(range(10,20))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [115]:
x = np.array(range(10)).reshape((5,2))
x

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [116]:
y = np.array(range(10,20)).reshape((5,2))
y

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])


    - horizontally or column-wise with hstack
    
    - vertically or row-wise with vstack.
    

In [117]:
np.hstack((x,y))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13],
       [ 4,  5, 14, 15],
       [ 6,  7, 16, 17],
       [ 8,  9, 18, 19]])

In [118]:
np.vstack((x,y))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

## Basic Arithmetic Operations.

In [120]:
x = np.array(range(10)).reshape((5,2))
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [121]:
y = np.array(range(10,20)).reshape((5,2))
y

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [125]:
x + y

x - y

x * y

x / y

array([[0.        , 0.09090909],
       [0.16666667, 0.23076923],
       [0.28571429, 0.33333333],
       [0.375     , 0.41176471],
       [0.44444444, 0.47368421]])

## Matrix Multiplication

In [127]:
# this will give an error because the sizes do not ift for matrix multiplication.
x.dot(y)

ValueError: shapes (5,2) and (5,2) not aligned: 2 (dim 1) != 5 (dim 0)

In [128]:
yt = y.T

x.dot(yt)

array([[ 11,  13,  15,  17,  19],
       [ 53,  63,  73,  83,  93],
       [ 95, 113, 131, 149, 167],
       [137, 163, 189, 215, 241],
       [179, 213, 247, 281, 315]])

## Advanced Broadcasting

In NumPy, broadcasting allows mathematical __operations of arrays of different shapes.__

NumPy can 'broadcast' the smaller array across the larger array so that they have compatible shapes.

This is very useful since we often have arrays of different shapes, and it would be cumbersome always to have to match them. ; cumbersome -> 성가신



### Broadcasting Rule One

The arrays must have __matching dimension sizes.__ A match means that either the dimension sizes are the smae OR at least one of the arrays has that dimension being 1.

When one of the dimensions is 1, NumPy will expand that dimension to be the same dimensions as the other array, so that they can match up

 - array1 with shpae (3, 4, 5) would match with array 2 with shape ( 3, 4, 1) Since the third dimension of array 2 can be expanded to be of size 5.
 
 - array3 with shape (7, 1, 10) woudl match with array 4 with shape (1, 10, 10). the second dimension of array can be expanded to 10, and the first dimension of array4 can be extended to 7
 
 - but array5 with shape (1,2,3) wouldn't match with array6 with shape (1, 2, 6) because the third dimensions are not equal, and __neither of them is 1.__
 
 

### Broadcasting Rule Two

Thge array with fewer dimensions will have __additional dimensions of size 1 prepended,__ until the dimensions are the same size as the other array. 

    - array 1 with shape (3, 4, 5) would match with array2 with shape (4,5). Numpy will expand the shape of array2 to be (1, 4, 5). And as mentioned earlier,shape (3, 4, 5) will match with shape (1, 4, 5)
    
    - array 3 with shape (5, 6, 7, 8) would match with array4 with shape (7,8). Numpy will expand the shape (1, 2, 3, 4) would match with array6 with shape (1,). The shape of array 6 will be expanded to (1, 1, 1, 1).
    

In [129]:
x = np.array(range(10)).reshape((5,2))
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [130]:
x * 2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [131]:
x + 5

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [133]:
x = np.array(range(10)).reshape((5,2))
x

y = np.array([2, 5])
y

array([2, 5])

In [134]:
print(x.shape)
print(y.shape)

(5, 2)
(2,)


In [135]:
x + y

array([[ 2,  6],
       [ 4,  8],
       [ 6, 10],
       [ 8, 12],
       [10, 14]])

In [138]:
x = np.array(range(10)).reshape((5,2))
x

y = np.array([1,2,3,4,5]).reshape(-1, 1)
y

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [139]:
print(x.shape)
print(y.shape)

(5, 2)
(5, 1)


In [140]:
x+y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11],
       [13, 14]])

## Random Number Generation

Besides array operations, another powerful data science function in NumPy is the _random_ libraries. We often use it to generate pseduo-random numbers, which can be used for simulations, sample data creation, and random sampling.

For example, 

    ### the _random.uniform_ returns a random array of a specified size with elements uniformly distributed over the interval [low, high]. 

    ### the _random.rand_ creates an arrayof the given shape and populates it with random samples from a uniform distribution over [0, 1).



In [146]:
np.random.uniform(low=0.0, high=1.0, size=10)

np.random.uniform(low=0.0, high=1.0, size=(5,5))

np.random.rand(5, 5) 

array([[0.46447991, 0.45460262, 0.22781041, 0.73702112, 0.40281865],
       [0.81589644, 0.31343341, 0.91532552, 0.07304937, 0.15475495],
       [0.25522286, 0.03759126, 0.95288576, 0.78161539, 0.52026315],
       [0.64386756, 0.6460969 , 0.61408443, 0.33886403, 0.08890843],
       [0.95796952, 0.6082194 , 0.68404283, 0.58455587, 0.99427273]])

Similary, the _random.normal_ draws array with elements as random samples from a _normal (Gaussian) distribution._ 

The loc is the mean while the scale is the standard deviation of the distribution

The _random.randn_ draws a random array with elements from the standard normal distribution (the noraml distribution of mean 0 and variance 1).

In [147]:
np.random.normal(loc=5, scale=10, size=10)

np.random.randn(5, 5)

array([[-3.12604774,  0.20319833,  0.4518162 , -1.34623737,  0.13275067],
       [ 0.50542984,  0.31861385, -0.74103261, -1.08425648, -0.33631433],
       [ 0.11114213,  0.32196543, -1.6829088 ,  1.49615836, -1.01566532],
       [ 0.24398852,  1.1713344 ,  1.36403457, -0.60662318, -0.50088892],
       [-1.08433866, -0.51460139, -0.08031194, -0.6218903 , -0.42339868]])

Besides drawing numbers from statistical distributions, we can also draw _random integers_ from a 'discrete uniform' distribution.

In [158]:
#np.random.seed(42)
np.random.randint(low=5, high=20, size=10) # random integer.

array([ 5, 16, 14, 10, 17, 16, 13,  5, 15, 15])

## Arange and linspace

We've been using the range funciton a lot in Python. In NumPy, we have a similar function - the _arange_ function.

Arange returns evenly spaced values with in a given interval [start, stop).

For an integer input, the function is equivalent to the Python built-in _range_ function, but returns a NumPy array rather than a list.

So why do we need arange?

One of the improvements of arange over range is the support for floating-point values.


If we try to create a range sequence with decimal ;소수의 start and stop positions, it will return errors.

But arange can handle that.



In [162]:
range(0, 10.5, 0.25) # range doesnt' support decimals.

np.arange(0, 10.5, step=0.25)

TypeError: 'float' object cannot be interpreted as an integer

An alternative to arange is _numpy.linspace creates an array of evenly spaced numbers over a specified interval.

For example, we can generate num = 101 equally spaced samples ranging from 0 to 10.

In [163]:
np.linspace(start=0, stop=10, num=101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

## Min and Max Index



In [166]:
x = np.random.randn(10)
x

array([ 0.09176078, -1.98756891, -0.21967189,  0.35711257,  1.47789404,
       -0.51827022, -0.8084936 , -0.50175704,  0.91540212,  0.32875111])

In [170]:
ind = np.argmin(x) # this gives the index with the minimum value.
print('The index of the minimum value: {}'.format(ind))
print(f'The value of the minimum: {x[ind]}')

ind = np.argmax(x) # this gives the index with the maximum value.
print('The index of the minimum value: {}'.format(ind))
print(f'The value of the minimum: {x[ind]}')

The index of the minimum value: 1
The value of the minimum: -1.9875689146008928
The index of the minimum value: 4
The value of the minimum: 1.477894044741516


In [172]:
x = np.random.randn(5,3)
x

array([[-0.80227727, -0.16128571,  0.40405086],
       [ 1.8861859 ,  0.17457781,  0.25755039],
       [-0.07444592, -1.91877122, -0.02651388],
       [ 0.06023021,  2.46324211, -0.19236096],
       [ 0.30154734, -0.03471177, -1.16867804]])

In [173]:
np.argmin(x, axis=0)

array([0, 2, 4], dtype=int64)

In [174]:
np.argmin(x, axis=1)

array([0, 1, 1, 2, 2], dtype=int64)

## Sort

In [175]:
x = np.random.randn(10)

In [176]:
x

array([ 1.14282281,  0.75193303,  0.79103195, -0.90938745,  1.40279431,
       -1.40185106,  0.58685709,  2.19045563, -0.99053633, -0.56629773])

In [178]:
# sort it in ascending order as below
np.sort(x)

array([-1.40185106, -0.99053633, -0.90938745, -0.56629773,  0.58685709,
        0.75193303,  0.79103195,  1.14282281,  1.40279431,  2.19045563])

## Copy

In [179]:
x = np.array([1, 2])
y = x
z = np.copy(x)

In [180]:
x[0] = 10
print(y[0])
print(z[0])

10
1
